/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analizadorLexico;

import java.io.IOException;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackG = new javax.swing.JPanel();
        pnlLateral = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlPie = new javax.swing.JPanel();
        lblEquipo = new javax.swing.JLabel();
        pnlAnalizar = new javax.swing.JPanel();
        lblAnalizar = new javax.swing.JLabel();
        pnlLimpiar = new javax.swing.JPanel();
        lblLimpiar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAnalisis = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTokens = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        pnlBackG.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLateral.setBackground(new java.awt.Color(29, 45, 80));
        pnlLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Analizador Léxico");
        pnlLateral.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 11, 170, 36));
        pnlLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));

        pnlPie.setBackground(new java.awt.Color(48, 71, 115));

        lblEquipo.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblEquipo.setForeground(new java.awt.Color(255, 255, 255));
        lblEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEquipo.setText("EQUIPO 4");

        javax.swing.GroupLayout pnlPieLayout = new javax.swing.GroupLayout(pnlPie);
        pnlPie.setLayout(pnlPieLayout);
        pnlPieLayout.setHorizontalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addComponent(lblEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlPieLayout.setVerticalGroup(
            pnlPieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEquipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlLateral.add(pnlPie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 150, 30));

        pnlAnalizar.setBackground(new java.awt.Color(48, 71, 115));
        pnlAnalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAnalizarMouseClicked(evt);
            }
        });

        lblAnalizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAnalizar.setForeground(new java.awt.Color(255, 255, 255));
        lblAnalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnalizar.setText("Analizar");

        javax.swing.GroupLayout pnlAnalizarLayout = new javax.swing.GroupLayout(pnlAnalizar);
        pnlAnalizar.setLayout(pnlAnalizarLayout);
        pnlAnalizarLayout.setHorizontalGroup(
            pnlAnalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(pnlAnalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAnalizarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblAnalizar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlAnalizarLayout.setVerticalGroup(
            pnlAnalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(pnlAnalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAnalizarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblAnalizar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlLateral.add(pnlAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 40));

        pnlLimpiar.setBackground(new java.awt.Color(48, 71, 115));
        pnlLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLimpiarMouseClicked(evt);
            }
        });

        lblLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiar.setText("Limpiar");

        javax.swing.GroupLayout pnlLimpiarLayout = new javax.swing.GroupLayout(pnlLimpiar);
        pnlLimpiar.setLayout(pnlLimpiarLayout);
        pnlLimpiarLayout.setHorizontalGroup(
            pnlLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLimpiarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlLimpiarLayout.setVerticalGroup(
            pnlLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLimpiarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLimpiar)
                .addContainerGap())
        );

        pnlLateral.add(pnlLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 40));

        pnlBackG.add(pnlLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresa Texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        txtAnalisis.setColumns(20);
        txtAnalisis.setRows(5);
        jScrollPane1.setViewportView(txtAnalisis);

        pnlBackG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 620, 260));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tblTokens.setAutoCreateRowSorter(true);
        tblTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Token", "Lexema", "Linea", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTokens.setGridColor(new java.awt.Color(255, 255, 255));
        tblTokens.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jScrollPane2.setViewportView(tblTokens);
        if (tblTokens.getColumnModel().getColumnCount() > 0) {
            tblTokens.getColumnModel().getColumn(0).setResizable(false);
            tblTokens.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblTokens.getColumnModel().getColumn(1).setResizable(false);
            tblTokens.getColumnModel().getColumn(1).setPreferredWidth(15);
            tblTokens.getColumnModel().getColumn(2).setResizable(false);
            tblTokens.getColumnModel().getColumn(2).setPreferredWidth(3);
            tblTokens.getColumnModel().getColumn(3).setResizable(false);
            tblTokens.getColumnModel().getColumn(3).setPreferredWidth(3);
        }

        pnlBackG.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 620, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_close_window_25px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnlBackG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlAnalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAnalizarMouseClicked
         try {
            archivos ar = new archivos();
            ar.probarLexerFile(txtAnalisis,tblTokens);// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnlAnalizarMouseClicked

    private void pnlLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLimpiarMouseClicked
        limpiar();
    }//GEN-LAST:event_pnlLimpiarMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    void limpiar(){
        txtAnalisis.setText("");
        eliminar();
    }
    
    
    public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) tblTokens.getModel();
        tb.setRowCount(0);
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAnalizar;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblLimpiar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAnalizar;
    private javax.swing.JPanel pnlBackG;
    private javax.swing.JPanel pnlLateral;
    private javax.swing.JPanel pnlLimpiar;
    private javax.swing.JPanel pnlPie;
    private javax.swing.JTable tblTokens;
    private javax.swing.JTextArea txtAnalisis;
    // End of variables declaration//GEN-END:variables
}
